[package]
name = "black_scholes"
version = "0.2.0"
edition = "2024"
published-at = "0x1637ddc0495a8833ebd580224dad7154dfb33477f73d2c7fb41e2b350efa55b3"

[dependencies]
gaussian = { git = "https://github.com/Evan-Kim2028/move-gaussian.git", rev = "v0.9.0" }

[addresses]
black_scholes = "0x0"
